# Generated by Django 6.0.3 on 2026-03-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='nota',
            field=models.IntegerField(default=0),
        ),
    ]
