# Generated by Django 6.0.3 on 2026-03-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='comentario',
            field=models.CharField(default='', max_length=500),
        ),
    ]
